# frozen_string_literal: true

require 'graphql'

module GraphQL
  module Derivation
    module Rails
      # SPEC.md §8.2. A minimal per-namespace `GraphQL::Schema` subclass with no
      # query root and no application types pre-registered. It exists only to:
      #
      #   1. Hold every anonymous InputObject generated by the ControllerConcern
      #      so they are introspectable (for TypeScript codegen) without
      #      polluting the application schema.
      #   2. Provide the query context used to coerce request input
      #      (`coerce_input` reads argument visibility through a context).
      #
      # graphql-ruby `GraphQL::Schema` subclasses are used as singletons via
      # class methods (`MySchema.execute(...)`, never `MySchema.new`), so
      # `.for(namespace)` returns/caches a *subclass* per namespace, not an
      # instance. The cache lives on `ArgumentSchema` itself, keyed by namespace.
      #
      # On orphan-type visibility: InputObjects cannot be `orphan_types`
      # (graphql-ruby restricts that to Object types) and, being unreachable
      # from any root, are filtered out of the visibility-profile-backed
      # `Schema.types`. The supported registration channel is `extra_types`,
      # which is what `Schema#to_definition` (the SDL the codegen plugin
      # consumes) walks. So `registered_input_objects` and `to_definition` are
      # the introspection surface here, not `Schema.types`.
      class ArgumentSchema < GraphQL::Schema
        # Class-level behaviour mixed into each per-namespace ArgumentSchema
        # subclass. Extracted into a module so `build_namespace_schema` stays a
        # thin factory.
        module NamespaceSchema
          attr_reader :argument_namespace

          # Registers an anonymous InputObject as an orphan/extra type so it
          # shows up in this schema's SDL for codegen. Idempotent: re-registering
          # the same class is a no-op.
          def register_input_object(input_object_class)
            return if registered_input_objects.include?(input_object_class)

            registered_input_objects << input_object_class
            extra_types(*registered_input_objects)
          end

          def registered_input_objects
            @registered_input_objects ||= []
          end

          # The query context used to coerce request input. A NullContext bound
          # to this schema gives a NullWarden (all types visible), which is
          # exactly SPEC.md §8.2's requirement.
          def coercion_context
            GraphQL::Query::NullContext.new(schema: self)
          end
        end

        class << self
          # Returns (creating and caching on first use) the schema subclass for
          # +namespace+. One subclass per namespace, cached for the process
          # lifetime. `nil` collapses to the default namespace `:default`
          # (SPEC.md §8.2).
          def for(namespace)
            namespace ||= :default
            schemas[namespace] ||= build_namespace_schema(namespace)
          end

          # Test/introspection seam: forget all cached per-namespace schemas.
          # Not part of the public runtime API -- used to keep specs isolated.
          def reset!
            @schemas = {}
          end

          private

          def schemas
            @schemas ||= {}
          end

          def build_namespace_schema(namespace)
            schema = Class.new(self)
            schema.extend(NamespaceSchema)
            schema.instance_variable_set(:@argument_namespace, namespace)
            schema
          end
        end
      end
    end
  end
end
